"""autogenerated by genpy from corobot_phidgetIK/BumperMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BumperMsg(genpy.Message):
  _md5sum = "e6f554580caa3ea2c4e88f283d5e3364"
  _type = "corobot_phidgetIK/BumperMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Deprecated. Prefer to use the one in corobot_msgs package, which is exactly the same

int8 bumpers_count
int8 value0
int8 value1
int8 value2
int8 value3

"""
  __slots__ = ['bumpers_count','value0','value1','value2','value3']
  _slot_types = ['int8','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bumpers_count,value0,value1,value2,value3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BumperMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.bumpers_count is None:
        self.bumpers_count = 0
      if self.value0 is None:
        self.value0 = 0
      if self.value1 is None:
        self.value1 = 0
      if self.value2 is None:
        self.value2 = 0
      if self.value3 is None:
        self.value3 = 0
    else:
      self.bumpers_count = 0
      self.value0 = 0
      self.value1 = 0
      self.value2 = 0
      self.value3 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5b.pack(_x.bumpers_count, _x.value0, _x.value1, _x.value2, _x.value3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.bumpers_count, _x.value0, _x.value1, _x.value2, _x.value3,) = _struct_5b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5b.pack(_x.bumpers_count, _x.value0, _x.value1, _x.value2, _x.value3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.bumpers_count, _x.value0, _x.value1, _x.value2, _x.value3,) = _struct_5b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5b = struct.Struct("<5b")
