"""autogenerated by genpy from corobot_phidgetIK/IrMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class IrMsg(genpy.Message):
  _md5sum = "46919f88799a3d678e8e0d18c2cd02f1"
  _type = "corobot_phidgetIK/IrMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Deprecated. Prefer to use the one in corobot_msgs package, which is exactly the same

float32 voltage1
float32 voltage2
float32 range1
float32 range2

"""
  __slots__ = ['voltage1','voltage2','range1','range2']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       voltage1,voltage2,range1,range2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IrMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.voltage1 is None:
        self.voltage1 = 0.
      if self.voltage2 is None:
        self.voltage2 = 0.
      if self.range1 is None:
        self.range1 = 0.
      if self.range2 is None:
        self.range2 = 0.
    else:
      self.voltage1 = 0.
      self.voltage2 = 0.
      self.range1 = 0.
      self.range2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.voltage1, _x.voltage2, _x.range1, _x.range2))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.voltage1, _x.voltage2, _x.range1, _x.range2,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.voltage1, _x.voltage2, _x.range1, _x.range2))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.voltage1, _x.voltage2, _x.range1, _x.range2,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4f = struct.Struct("<4f")
