"""autogenerated by genpy from corobot_teleop/takepic.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class takepic(genpy.Message):
  _md5sum = "802817317afdd58e6e9fd4be92bf0d57"
  _type = "corobot_teleop/takepic"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 camera_index
int32 note
bool take

"""
  __slots__ = ['camera_index','note','take']
  _slot_types = ['int32','int32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       camera_index,note,take

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(takepic, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.camera_index is None:
        self.camera_index = 0
      if self.note is None:
        self.note = 0
      if self.take is None:
        self.take = False
    else:
      self.camera_index = 0
      self.note = 0
      self.take = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2iB.pack(_x.camera_index, _x.note, _x.take))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.camera_index, _x.note, _x.take,) = _struct_2iB.unpack(str[start:end])
      self.take = bool(self.take)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2iB.pack(_x.camera_index, _x.note, _x.take))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.camera_index, _x.note, _x.take,) = _struct_2iB.unpack(str[start:end])
      self.take = bool(self.take)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2iB = struct.Struct("<2iB")
